name: Predict Lotto Numbers and Update README

on:
  schedule:
    - cron: '0 9 * * 1'  # 매주 월요일 UTC 시간 기준 09:00 (한국 시간 오후 6시)
  workflow_dispatch:

jobs:
  predict-and-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.5'

    - name: Install dependencies
      run: |
        pip install datasets transformers numpy torch==2.1.0 sklearn

    - name: Predict Lotto Numbers
      run: python inference.py

    - name: Update README
      run: python update_predicted_lotto_numbers_to_readme.py

    - name: Commit and Push Changes
      run: |
        git config --global user.name 'l-yohai'
        git config --global user.email 'yohan9612@naver.com'
        git add README.md
        git commit -m "Update README with predicted lotto numbers"
        git push
